export { default as Navbar } from './Navbar/index'
export { default as Sidebar } from './Sidebar/index'
export { default as Promos } from './Promos/index'
export { default as Blog } from './Blog/index'
export {default as Banner } from './Banner/index'
export {default as OnlineWkout } from './Onlinewkout/index'
